// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UHRGKyEzhUd4NC_zILTja92tvCPUSsU',
    appId: '1:230642052811:web:9a2d82c378a6542bfb754e',
    messagingSenderId: '230642052811',
    projectId: 'trace-raffine',
    authDomain: 'trace-raffine.firebaseapp.com',
    storageBucket: 'trace-raffine.firebasestorage.app',
    measurementId: 'G-RTPM04YGLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuD5IeMZyQSx5YAvFY5-NeRpx2nMWWdFo',
    appId: '1:230642052811:android:9d0811648df0cebbfb754e',
    messagingSenderId: '230642052811',
    projectId: 'trace-raffine',
    storageBucket: 'trace-raffine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLh2O01XaobgkoH_lcTcNEk9Kvm7xKD0',
    appId: '1:230642052811:ios:6ba81e715cfb0385fb754e',
    messagingSenderId: '230642052811',
    projectId: 'trace-raffine',
    storageBucket: 'trace-raffine.firebasestorage.app',
    iosBundleId: 'com.trace.raffine.traceRaffine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfLh2O01XaobgkoH_lcTcNEk9Kvm7xKD0',
    appId: '1:230642052811:ios:6ba81e715cfb0385fb754e',
    messagingSenderId: '230642052811',
    projectId: 'trace-raffine',
    storageBucket: 'trace-raffine.firebasestorage.app',
    iosBundleId: 'com.trace.raffine.traceRaffine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0UHRGKyEzhUd4NC_zILTja92tvCPUSsU',
    appId: '1:230642052811:web:ba2c70209cfe7be1fb754e',
    messagingSenderId: '230642052811',
    projectId: 'trace-raffine',
    authDomain: 'trace-raffine.firebaseapp.com',
    storageBucket: 'trace-raffine.firebasestorage.app',
    measurementId: 'G-7GCRMTRW80',
  );
}
